language: node_js # set the language of the project to be deployed
node_js: #using nodejs stable version to build the project
  - "stable"
cache: # caching the node_modules folder 
  directories:
    - node_modules
script:
  - npm test
  - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token # Set in the settings page of your repository, as a secure variable
  local_dir: build
  on:
    branch: master
